#!/usr/bin/env bash

################################################################################
#
# This script implements a deploy hook for certbot,
# to copy TLS certificats on renewal.
# This script depends on the presence of /usr/local/sbin/tls-openldap
# for the actual copying.
#
# FreeBSD: /usr/local/etc/letsencrypt/renewal-hooks/deploy/copy-certs
# Debian : /etc/letsencrypt/renewal-hooks/deploy/copy-certs
# CentOS : /etc/letsencrypt/renewal-hooks/deploy/copy-certs
#
# More info: https://www.librobert.net/book/internet
#
################################################################################
#
# Copyright (c) 2020 Robert LA LAU < https://www.librobert.net/ >
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
################################################################################

set -e

unknown() {
	echo "Unknown system."
	exit 1
}

uname=$(uname)
case ${uname} in
	FreeBSD)
		system=freebsd
		;;
	Linux)
		if [ -f /etc/os-release ]; then
			system=$(source /etc/os-release; echo ${ID})
		else
			unknown
		fi
		;;
	*)
		unknown
		;;
esac
unset uname

for dom in ${RENEWED_DOMAINS}; do
	case ${dom} in
		ldap.example.com)
			env system=${system} /usr/local/sbin/tls-openldap
			case ${system} in
				freebsd)
					service slapd restart
					;;
				ubuntu|centos)
					systemctl restart slapd
					;;
				gentoo)
					rc-service slapd restart
					;;
			esac
			;;
	esac
done
